### ISSUE TITLE
ERROR in Error: Unexpected value 'Draggable in ./node_modules/ng2-drag-drop/src/directives/draggable.directive.d.ts' declared by the module 'Ng2DragDropModule in ./node_modules/ng2-drag-drop/src/ng2-drag-drop.module.d.ts'. Please add a @Pipe/@Directive/@Component annotation.

### ISSUE THREAD

**Issue by MarkKewley** [ObaidUrRehman/ng2-drag-drop#95]
Seems to have just showed up with our recent build using angluar-cli:
e.g.:
`ng build --prod`

`ERROR in Error: Unexpected value 'Draggable in ./node_modules/ng2-drag-drop/src/directives/draggable.directive.d.ts' declared by the module 'Ng2DragDropModule in ./node_modules/ng2-drag-drop/src/ng2-drag-drop.module.d.ts'. Please add a @Pipe/@Directive/@Component annotation.
    at Error (native)
    at syntaxError (/opt/atlassian/pipelines/agent/build/node_modules/@angular/compiler/bundles/compiler.umd.js:1725:34)
    at ./node_modules/@angular/compiler/bundles/compiler.umd.js:15465:40
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/opt/atlassian/pipelines/agent/build/node_modules/@angular/compiler/bundles/compiler.umd.js:15447:54)
    at addNgModule (/opt/atlassian/pipelines/agent/build/node_modules/@angular/compiler/bundles/compiler.umd.js:24241:58)
    at ./node_modules/@angular/compiler/bundles/compiler.umd.js:24252:14
    at Array.forEach (native)
    at _createNgModules (/opt/atlassian/pipelines/agent/build/node_modules/@angular/compiler/bundles/compiler.umd.js:24251:26)
    at analyzeNgModules (/opt/atlassian/pipelines/agent/build/node_modules/@angular/compiler/bundles/compiler.umd.js:24126:14)
    at analyzeAndValidateNgModules (/opt/atlassian/pipelines/agent/build/node_modules/@angular/compiler/bundles/compiler.umd.js:24136:35)
    at AotCompiler.analyzeModulesAsync (/opt/atlassian/pipelines/agent/build/node_modules/@angular/compiler/bundles/compiler.umd.js:23772:46)
    at CodeGenerator.codegen (/opt/atlassian/pipelines/agent/build/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (/opt/atlassian/pipelines/agent/build/node_modules/@angular/compiler-cli/src/ngtools_api.js:73:30)
    at _donePromise.Promise.resolve.then (/opt/atlassian/pipelines/agent/build/node_modules/@ngtools/webpack/src/plugin.js:386:44)`

**Comment by ObaidUrRehman** [comment]
@MarkKewley what version of Angular/CLI are you using?

**Comment by MarkKewley** [comment]
1.4.1 it looks like

**Comment by ObaidUrRehman** [comment]
Fixed in v2.8.0. It was a build issue.
Sorry for the inconvenience.

**Comment by MarkKewley** [comment]
Thanks Obaid, just verified appears to work now
